### PR TITLE
Fix benchmarks and add benchmark for getting a node

### PR DESCRIPTION
**Pull request by iand**
Fix `BenchmarkFind` which was broken in [47873c3](https://github.com/filecoin-project/go-hamt-ipld/commit/47873c31a85317ba3926848a12df34578a77aa2d) due to a double encoding of the Deferred values in the test.

Add a benchmark for getting a node which gives us a view of unmarshalling costs.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]
LGTM. Any chance you could add CI to this repo as well while you're at it?

**Comment by iand** [comment]
Not sure I understand the CI request. It already runs the standard CI actions https://github.com/filecoin-project/go-hamt-ipld/actions

**Comment by Stebalien** [comment]
Hm. Well, the checks aren't showing up on this PR. Maybe we need to enable it for forks?

**Comment by Stebalien** [comment]
Ok, I'm confused. The actions _should_ have run. I'm just going to merge it, I guess.

**Comment by Stebalien** [comment]
Probably related to github's issues this morning.

**Pull request merged**
