### PR TITLE
use of SetRaw constructs malformed HAMT

### PR DESCRIPTION
**Pull request by b5**
This is mainly to get a discussion going with a failing test. Seems the Set/FindRaw methods aren't tested and don't seem to be working as expected.

running this test fails with:

```
$ go test --run TestPutRaw
--- FAIL: TestPutRaw (0.00s)
    hamt_test.go:937:
        	Error Trace:	hamt_test.go:937
        	Error:      	Received unexpected error:
        	            	failed to read deferred field: unexpected EOF
        	Test:       	TestPutRaw
FAIL
exit status 1
FAIL	github.com/filecoin-project/go-hamt-ipld/v3	0.149s
```

I don't have the bandwidth to find the proper fix, but could update this PR to _remove_ the `Raw` methods if that helps. The way I've been working around it is to have all values written to the HAMT implement the `CBOR` marshaling interface

### CODE REVIEW

**Comment by rvagg** [comment]
+1 to removing *Raw if we're not using it at all in Lotus, IIRC there's some hacky code in here to accommodate them that could probably be unwound if they're removed.

**Comment by b5** [comment]
Thanks for the feedback @rvagg! sorry for the delay, just got around to removing the methods.

**Comment by b5** [comment]
... nevermind, this API is used a _lot_ by tests. I'd say removing the API might not be the way to go?

**Comment by rvagg** [comment]
oh, and those look like my tests .. how about just lower-casing it?

The tests that are using it aren't doing it because it's a practical API, but simply to test HAMT layout forms without the unnecessary overhead of building valid CBOR entries.

**Pull request closed without merging**
