### PR TITLE
add a method for finding the path through a hamt

### PR DESCRIPTION
**Pull request by tobowers**
We have the need to send in "proof of hamt" in a way... that is to show that your key does indeed descend from the tip of a hamt. Since the methods like isShard and loadChild are not exported, it's difficult to do ontop of this library.

This PR exposes a method to get all the nodes for a key so that you could then later prove that your key is included in the hamt.

### CODE REVIEW

**Comment by warpfork** [comment]
This looks reasonable to me at first glance.... maybe a ping to @whyrusleeping as the main progenitor of this, and maybe to @rvagg for interest in APIs around advanced layouts in general

**Comment by rvagg** [comment]
A ton of copypasta in here from `getValue`, that suggests its time to make the access method generic and reuse the same logic instead of duplicating it.

**Comment by tobowers** [comment]
I’m happy to do that work, but I’d love some direction there before
starting. What’s the reason for the callback over more direct recursion?
-- 
Topper Bowers

topper@toppingdesign.com
github.com/tobowers
linkedin.com/in/topperbowers

**Comment by rvagg** [comment]
yeah, that one's beyond me, perhaps to fit in with something Filecoin needs from it

**Comment by tobowers** [comment]
@rvagg since no one was commenting (fair, it is the holidays :)). I did a refactor to just have a single method. It does more work on a standard find, but the benchmarks were really comparable.

**Comment by rvagg** [comment]
lgtm, but this is @whyrusleeping's wheelhouse so it'll have to wait for him

**Comment by tobowers** [comment]
ping @whyrusleeping

**Comment by whyrusleeping** [comment]
Oh man, I havent looked at the PRs here for a while, i'm sorry.
This looks reasonable to me, though the only concern i have after just having spent a bunch of time in perf land, is that this adds extra allocations to find calls. Which may eventually become a problem, in which case we could just duplicate some code (which i see was the original design), or add an optional callback. 

In any case, i'm happy to merge this when the merge conflict is resolved, and sorry for the delay

**Comment by tobowers** [comment]
closing this for now as it's not neccesary for us anymore. We can revisit.

**Pull request closed without merging**
